name: FFA.Test.01
favicon: null
layout_spectrum: 0.5531860666815192
typography_spectrum: 0.29500077827833593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6557805279735476
  lightness: 0.09495682525448501
  saturation: 0.3036929510999471
  rhythmicContrast: 0.17879629647359252
purpose: []
